controllers:
    resource: ../../src/Controller/
    type: annotation
    # prefix: _locale
    # name_prefix: locale
    # trailing_slash_on_root: false
    # requirements:
    #    _locale: 'en|da|sv|no'


kernel:
    resource: ../../src/Kernel.php
    type: annotation
