controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: 'en|da|sv|no'

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\DefaultController::index
    locale: en
    requirements:
        _locale:  da|en|no|sv


