# config/routes.yaml

controllers:
#<<<<<<< ours
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: 'en|da|sv|no'

api:
    resource: ../src/Controller/Api*
    type: annotation

webapi:
    resource: ../src/Controller/Webapi*
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


# Omdirigerer til /{_locale}/
#
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'default'
        permanent: true

offline:
    path: /offline
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'static/offline.html.twig'

        # the response status code (default: 200)
        statusCode: 503

noscript:
    path: /noscript
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'static/noscript.html.twig'

        # the response status code (default: 200)
        # statusCode: 503

about:
    path: /{_locale}/about
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'static/about.html.twig'

        # the response status code (default: 200)
        # statusCode: 503

manifest:
    path: /manifest.jsonnn
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        # the path of the template to render
        template:  'static/manifest.html.twig'

        # the response status code (default: 200)
        # statusCode: 503


#=======
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute
#>>>>>>> theirs
