
controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: 'en|da|sv|no'

api:
    resource: ../src/Controller/Api*
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


# Omdirigerer til /{_locale}/
#
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'default'
        permanent: true  


