# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: da
    app_locales: da|sv|no|en
    app.supported_locales: da|en|no|sv
    app.icon.locked: '&#x1F512;'
    app.icon.unlocked: '&#x1F513;'

    app.ievent.tags:
        - BIRTH:  No01
        - DEATH:  No02
        - MARR:   No03

twig:
    globals:
        author: "Michael Lindhardt Rasmussen"
        product: "Codename Overlund"
        version: "Version: 0.1.0 alpha"
        description: "Web-based Genealogy Application"
        copyright: "© 2020-22 Filicis Software - Michael Lindhardt Rasmussen"

# Iconer
#	- Alt overvejende i form af Emojis hentet fra søgemaskinen https://emojipedia.org/

        icon_locked:				          "\U0001F512"
        icon_unlocked: 				        "\U0001F513"
        icon_confidential:            "\U0001F910"		# Zipper-Mouth Face
        icon_private:					        "\U0001F6D1"		# Stop sign
        icon_person:                    '&#x1F9D1;'   # Person
        icon_male:                      '&#x1F468;'   # Man
        icon_female:                    '&#x1F469;'   # Woman
        icon_child:                     '&#x1F9D2;'   # Child
        icon_family:                     '&#x1F46A;'   # Family
        icon_researchers:
        icon_delete: 					           '&#x1F5D1;'   # Waste Basket
        icon_up:						             '&#x1F53A;'		# Red Triangle Pointed Up
        icon_down:						           '&#x1F53B;'		# Red Triangle Pointed Down
        icon_left:                        '&#x2B05;'    # Left Arrow
        icon_right:                       '&#x27A1;'    # Right Arrow
        icon_pedigree:

        icon_events:		          			'&#x1F5D3;'		# Spiral Calendar
#       icon_notes:						          '&#x1F5D2;'		#	Spiral Notepad
        icon_notes:						            '&#x1F4CB;'		#	Clipboard
        icon_sources:					'&#x1F4DA;'		# Books
        icon_media:						"🖼️"

        icon_date:                      '&#x1F4C5;'   # Calendar
        icon_address:					'&#x1F4E9;'   # Envelope with Arrow
        icon_place:						'&#x1F4CD;'   # Round Pushpin

        icon_identifier:                '&#x1F4DB;'   # Name Badge

        icon_internet:                  '&#x1F310;'     # Internet

        icon_new:						'&#x1F195;'		# New Sign
        icon_edit:						'&#x270F;'		# Pencil

        icon_names:						'&#x1F4C7;'		# Card Index
        icon_alias:						'&#x1F977;'		# Ninja
        icon_association:			    '&#x26D3;'		# Chains

        icon_ok:                        '&#x2714;'    # Check Mark
        icon_cancel:                    '&#x274C;'    # Cross Mark
        icon_help:                      '&#x2754;'    # White Question Mark
        icon_desktop:                   '&#x1F5A5;'    # White Question Mark
        icon_folder:                   '&#x1F4C1;'    # White Question Mark
        icon_edit1:                   '&#x2754;'    # White Question Mark
        icon_envelope:                  '&#x1F583;'     # Enveloper

        ievent_tags:
          - BIRTH:  No01
          - DEATH:  No02
          - MARR:   No03




services:
    Symfony\Component\Uid\Command\GenerateUlidCommand: ~
    Symfony\Component\Uid\Command\GenerateUuidCommand: ~
    Symfony\Component\Uid\Command\InspectUlidCommand: ~
    Symfony\Component\Uid\Command\InspectUuidCommand: ~

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
        # uncomment the next line if you are not using autoconfigure
        # tags: [kernel.event_subscriber]
